import { StyleSheet, TextInput } from 'react-native';
import { Button } from '../components/Button';

export const styles = StyleSheet.create({
  Tela: {
    width: '100%',
    height: 1300,
    backgroundColor: '#7ec5ffff',
    flex: 1,
    alignItems: 'center' as const,   
  },
   Box1: {
    boxSizing: 'border-box' as const,
    width: '80%',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginTop: '10%',
    backgroundColor: '#ffffff',
    borderColor: '#5f5f5fff',
    borderWidth: 2,
    marginBottom: 20,
  },
    Text:{
    fontSize: 15,
    fontWeight: 'bold' as const,
    textAlign: 'center' as const,
    textTransform: 'capitalize' as const,
    },
    TextInput: {
    backgroundColor: '#e6e6e6',
    width: '100%',
    height: 40,
    borderColor: '#5f5f5fff',
    borderWidth: 2,
    borderRadius: 5,
    paddingLeft: 10,
    marginBottom: 10,
    fontSize: 15,
    fontWeight: 'bold' as const,
    },
    Box2: {
    boxSizing: 'border-box' as const,
    width: '80%',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginTop: '10%',
    backgroundColor: '#ffffff',
    borderColor: '#5f5f5fff',
    borderWidth: 2,
    marginBottom: 20,
    },
    Button:{
      backgroundColor: '#007bff',
      borderRadius: 15,
      borderColor: 'black',
      borderWidth: 2,
      padding: 12,
      width: '50%',
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    ErroMsg:{
      color: 'red',
      fontWeight: 'bold' as const,
      marginBottom: 10,
      marginStart: 5,
      padding: 20,
      textAlign: 'center' as const,
    },
  });